= Lex Request/Response Java API

This repository contains Java API for Lambda function input event and response format for Amazon Lex. The data model is defined at http://docs.aws.amazon.com/lex/latest/dg/lambda-input-response-format.html.

This is in addition to the http://docs.aws.amazon.com/lex/latest/dg/programming-model.html[Lex model and runtime API] defined by the https://aws.amazon.com/sdk-for-java/[AWS Java SDK]. The model API allows to programmatically create bots, intent, and slot types. You can also use the model building API to manage, update, and delete resources for your bot. The runtime API is used to call a specific Amazon Lex bot to process utterances — user text or voice input.

The input event API is in `org.sample.aws.lex.request` package and the response API is in `org.sample.aws.lex.response` package.

== Install JAR locally

This API JAR can be installed in two ways:

. Clone the repo and build the JAR file:

    git clone https://github.com/arun-gupta/lex-java
    mvn package

. Install the pre-built JAR to maven:

    curl -O -L https://github.com/arun-gupta/lex-java/releases/download/0.1/lex-java-0.1.jar
    mvn install:install-file -Dfile=./lex-java-0.1.jar -DgroupId=org.sample.aws.lex -DartifactId=lex-java -Dversion=0.1 -Dpackaging=jar

== Maven depdendency

        <dependency>
            <groupId>org.sample.aws.lex</groupId>
            <artifactId>lex-java</artifactId>
            <version>0.1</version>
        </dependency>

